server:
  port: 8800
  
  
  
mybatis-plus:
  type-aliases-package: com.anzhi.system.entity
  mapper-locations: classpath:mapper/**/*.xml
  configuration:
    jdbc-type-for-null: null
  global-config:
    # 关闭 mybatis-plus的 banner
    banner: false

  
spring:
  application:
    name: anzhi-lampblack
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.147.129:3306/lampblackDB?serverTimezone=UTC&characterEncoding=utf8&useUnicode=true&useSSL=false
#   url: jdbc:mysql://192.168.147.129:3306/youyan?serverTimezone=UTC&characterEncoding=utf8&useUnicode=true&useSSL=false
    username: root
    password: root
    dbcp2:
      min-idle: 5 
      initial-size: 5
      max-total: 5
      max-wait-millis: 200 
#      
#  redis:
#    host: 127.0.0.1
#    port: 6379
#    password: 
#    jedis:
#      pool:
#        min-idle: 8
#        max-idle: 500
#        max-active: 2000
#        max-wait: 10000
#    timeout: 0
   
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/